name: Bump yarn versions

on:
  # schedule:
  # - cron: '0 12 3 * *'
  pull_request:
    types:
      - opened
      - closed
      - edited
      - reopened
      - synchronize

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - run: yarn install --immutable
      - run: ./update.sh
